RepositoryLanguage:
    type: enum
    config:
        values:
            eng-GB:
                value: eng-GB
                description: 'English (United Kingdom)'
            esp-ES:
                value: esp-ES
                description: Español
