imports:
    - { resource: views.yml }

ezpublish:

    locale_conversion:
        eng-GB: en-GB
        esp-ES: es-ES

    # HttpCache settings, By default 'local' (Symfony HttpCache Proxy), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: '%search_engine%'
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list:
            - site_en
            - site_es
            - slymfony
            - reactenclaw
            - worpindorf
            - slackelpuff
            - admin
        groups:
            site:
                - site_en
                - site_es
            site_group:
                - slymfony
                - reactenclaw
                - worpindorf
                - slackelpuff
            admin_group:
                - admin
        default_siteaccess: site_es
        match:
            Map\URI:
                slymfony: slymfony
                reactenclaw: reactenclaw
                worpindorf: worpindorf
                slackelpuff: slackelpuff
                admin: admin
            Compound\LogicalAnd:
                site_en_matches:
                    matchers:
                        Map\URI: { en: true }
                    match: site_en
                site_es_matches:
                    matchers:
                        Map\URI: { es: true }
                    match: site_es
    # System settings, read in following order: `default`, <siteaccess-group>, <siteacces>, and `global`
    # TIP: For multisite installations organize shared config into SiteAccess groups,
    #      on single-site you can place shared config under "default" for simplicity as shown below.

    url_alias:
        slug_converter:
            transformation: 'urlalias_lowercase'

ez_platform_standard_design:
    # makes Kernel default templates (in EzPublishCoreBundle/Resources/views) part of standard Design
    override_kernel_templates: true

ezdesign:
    design_list:
        default: [default]
        cloud: [cloud]
        slymfony: [slymfony]
        reactenclaw: [reactenclaw]
        worpindorf: [worpindorf]
        slackelpuff: [slackelpuff]